module Worldfactbook
  class NoCountryAvailable < StandardError; end

  class CountryCode
    attr_accessor :country

    def initialize(country)
      @country = country
      @codes = { 'world' => 'xx',
                'afghanistan' => 'af',
                'albania' => 'al',
                'algeria' => 'ag',
                'andorra' => 'an',
                'angola' => 'ao',
                'antarctica' => 'ay',
                'antigua' => 'ac',
                'barbuda' => 'ac',
                'antigua and barbuda' => 'ac',
                'argentina' => 'ar',
                'algeria' => 'ag',
                'armenia' => 'am',
                'algeria' => 'ag',
                'australia' => 'as',
                'austria' => 'au',
                'azerbaijan' => 'aj',
                'bahamas' => 'bf',
                'the bahamas' => 'bf',
                'bahrain' => 'ba',
                'bangladesh' => 'bg',                
                'barbados' => 'bb',
                'belarus' => 'bo',
                'belgium' => 'be',
                'belize' => 'bh',
                'benin' => 'bn',
                'bermuda' => 'bd',
                'bhutan' => 'bt',
                'bolivia' => 'bl',
                'bosnia' => 'bk',
                'herzegovina' => 'bk',
                'bosnia and herzegovina' => 'bk',
                'botswana' => 'bc',
                'brazil' => 'br',
                'brunei' => 'bx',
                'bulgaria' => 'bu',
                'burkina faso' => 'uv',
                'burma' => 'bm',
                'burundi' => 'by',
                'cambodia' => 'cb',
                'cameroon' => 'cm',
                'canada' => 'ca',
                'cape verde' => 'cv',
                'central african republic' => 'ct',
                'chad' => 'cd',
                'chile' => 'ci',
                'china' => 'ch',
                'colombia' => 'co',
                'comoros' => 'cn',
                'democratic republic of the congo' => 'cg',
                'republic of the congo' => 'cf',
                'costa rica' => 'cs',
                "cote d'ivoire" => 'iv',
                'croatia' => 'hr',
                'cuba' => 'cu',
                'cyprus' => 'cy',
                'czech republic' => 'ez',
                'denmark' => 'da',
                'djibouti' => 'dj',
                'dominica' => 'do',
                'dominican republic' => 'dr',
                'ecuador' => 'ec',
                'egypt' => 'eg',
                'el salvador' => 'es',
                'equatorial guinea' => 'ek',
                'eritrea' => 'er',
                'estonia' => 'en',
                'ethiopia' => 'et',
                'fiji' => 'fj',
                'finland' => 'fi',
                'france' => 'fr',
                'gabon' => 'gb',
                'the gambia' => 'gb',
                'gaza strip' => 'gz',
                'georgia' => 'gg',
                'germany' => 'gm',
                'ghana' => 'gh',
                'greece' => 'gr',
                'greenland' => 'gl',        
                'grenada' => 'gj',
                'guatemala' => 'gt',
                'guinea' => 'gv',
                'guinea-bissau' => 'pu',
                'guyana' => 'gy',
                'haiti' => 'ha',
                'honduras' => 'ho',
                'hong kong' => 'hk',
                'hungary' => 'hu',
                'iceland' => 'ic',
                'india' => 'in',
                'iran' => 'ir',
                'iraq' => 'iz',
                'ireland' => 'ei',
                'israel' => 'is',
                'italy' => 'it',
                'jamaica' => 'jm',
                'japan' => 'ja',
                'jordan' => 'jo',
                'kazakhstan' => 'kz',
                'kenya' => 'ke',
                'kiribati' => 'kr',
                'north korea' => 'kn',
                'south korea' => 'ks',
                'kosovo' => 'kv',
                'kuwait' => 'ku',
                'kyrgyzstan' => 'kg',
                'laos' => 'la',
                'latvia' => 'lg',
                'lebanon' => 'le',
                'lesotho' => 'lt',
                'liberia' => 'li',
                'libya' => 'ly',
                'liechtenstein' => 'ls',
                'lithuania' => 'lh',
                'luxembourg' => 'lu',
                'macedonia' => 'mk',
                'madagascar' => 'ma',
                'malawi' => 'mi',
                'malaysia' => 'my',
                'maldives' => 'mv',
                'mali' => 'ml',
                'malta' => 'mt',
                'marshall islands' => 'rm',
                'mauritania' => 'mr',
                'mauritius' => 'mp',
                'mexico' => 'mx',
                'micronesia' => 'fm',
                'moldova' => 'md',
                'monaco' => 'mn',
                'mongolia' => 'mg',
                'montenegro' => 'mj',
                'morocco' => 'mo',
                'moldova' => 'md',
                'mozambique' => 'mz',
                'nambia' => 'wa',
                'nauru' => 'nr',
                'nepal' => 'np',
                'netherlands' => 'nl',
                'new zealand' => 'nz',
                'nicaragua' => 'nu',
                'niger' => 'ng',
                'nigeria' => 'ni',
                'norway' => 'no',
                'oman' => 'mu',
                'pakistan' => 'pk',
                'palau' => 'ps',
                'panama' => 'pm',
                'papua new guinea' => 'pp',
                'paraguay' => 'pa',
                'peru' => 'pe',
                'philippines' => 'rp',
                'poland' => 'pl',
                'portugal' => 'po',
                'puerto rico' => 'rq',
                'qatar' => 'qa',
                'romania' => 'ro',
                'russia' => 'rs',
                'rwanda' => 'rw',
                'saint kitts and nevis' => 'sc',
                'saint lucia' => 'st',
                'saint vincent' => 'vc',        
                'the grenadines' => 'vc',
                'saint vincent and the grenadines' => 'vc',
                'samoa' => 'ws',
                'san marino' => 'sm',
                'sao tome' => 'tp',
                'principe' => 'tp',
                'sao tome and principe' => 'tp',
                'saudi arabia' => 'sa',
                'senegal' => 'sg',
                'serbia' => 'ri',
                'seychelles' => 'se',
                'sierra leone' => 'sl',
                'singapore' => 'sn',
                'slovakia' => 'lo',
                'slovenia' => 'si',
                'solomon islands' => 'bp',
                'somalia' => 'so',
                'south africa' => 'sf',
                'spain' => 'sp',
                'sri lanka' => 'ce',
                'sudan' => 'su',
                'suriname' => 'ns',
                'swaziland' => 'wz',
                'sweden' => 'sw',
                'switzerland' => 'sz',
                'syria' => 'sy',
                'taiwan' => 'tw',
                'tajikistan' => 'ti',
                'tanzania' => 'tz',
                'thailand' => 'th',
                'timor-leste' => 'tt',
                'togo' => 'to',
                'tonga' => 'tn',
                'trinidad' => 'td',
                'tobago' => 'td',
                'tunisia' => 'ts',
                'turkey' => 'tu',
                'turkmenistan' => 'tx',
                'tuvalu' => 'tv',
                'uganda' => 'ug',
                'ukraine' => 'up',
                'united arab emirates' => 'ae',
                'united kingdom' => 'uk',
                'united states' => 'us',
                'uruguay' => 'uy',
                'uzbekistan' => 'uz',
                'vanuatu' => 'nh',
                'venezuela' => 've',
                'vietnam' => 'vm',
                'west bank' => 'we',
                'yemen' => 'ym',
                'zambia' => 'za',
                'zimbabwe' => 'zi',
                'european union' => 'ee' }
    end

    def code
      if @codes.has_key?(@country)
        @codes.fetch(@country) 
      elsif @codes.has_value?(@country)
        return @country
      else
        raise NoCountryAvailable.new("#{@country} isn't available in the CIA World Factbook.")
      end
    end

    def list
      return @codes
    end
  end

end
